import { addDate, TIME_DAY } from "@zui/helpers";

const now = Date.now();
const start = now - (60 * TIME_DAY);
const randomInt = (min: number, max: number) => {
    return Math.floor(Math.random() * (max - min + 1)) + min;
};
const colors = ['var(--color-primary-500)', 'var(--color-secondary-500)', 'var(--color-warning-500)', 'var(--color-danger-500)', 'var(--color-success-500)', 'var(--color-important-500)', 'var(--color-special-500)'];
const events = [
    '早起',
    '喝一杯水',
    '洗澡',
    'Update your resume',
    'Clean out the garage',
    'Participate in a book club',
    '吃早饭',
    '回顾今天的目标',
    '检查邮件',
    '回复紧急信息',
    'Clean the kitchen',
    'Take out the trash',
    'Schedule a doctor\'s appointment',
    'Follow up on a project',
    'Pick up a package',
    'Listen to a podcast',
    'Write a letter',
    'Plan a family activity',
    'Buy a gift for someone',
    '参加团队会议',
    '进行项目A的工作',
    '打电话',
    '散步',
    'Declutter the living room',
    'Research upcoming events',
    'Enjoy a spa day at home',
    'Explore a new neighborhood',
    'Create a vision board',
    'Send birthday wishes',
    'Test a new fitness routine',
    'Practice mindfulness',
    'Share a meal with family',
    'Visit a local museum',
    '准备午饭',
    '阅读一章书',
    '短暂休息',
    '进行项目B的工作',
    '发送邀请',
    '更新日历',
    'Write down goals for the next month',
    'Plan a date night',
    'Attend a concert',
    'Write down things you are grateful for',
    'Spend time with pets',
    'Go fishing',
    'DIY a home project',
    '清理工作区域',
    '审核开支',
    '计划明天',
    '浇水',
    '洗衣服',
    '去买菜',
    'Host a dinner party',
    'Start a savings plan',
    'Read the news',
    'Plan a budget',
    '做晚饭',
    '看电影',
    '做运动',
    '冥想10分钟',
    'Take a day off',
    'Clean out the closet',
    'Watch a documentary',
    'Work on a personal project',
    '给朋友打电话',
    '整理文件',
    '写日记',
    '练习一个爱好',
    '骑自行车',
    '参加瑜伽课',
    '计划周末旅行',
    'Plan a picnic',
    'Clean the car',
    'Collect items for donation',
    'Watch a favorite TV show',
    'Take a scenic drive',
    '研究一个感兴趣的话题',
    '审核一个演示文稿',
    '发送感谢信',
    'Clean the bathroom',
    'Write down affirmations',
    'Practice a new language',
    'Take a photography walk',
    '留出时间进行自我关怀',
    '制作待办事项清单',
    'Go to the gym',
    'Research a recipe',
    'Go for a coffee',
    'Update social media',
    'Make an appointment with a stylist',
    'Volunteer for a local charity',
    'Organize a game night',
    'Attend a workshop',
    'Write a poem',
    'Catch up on sleep',
    'Experiment with new makeup looks',
    'Plan a road trip',
    'Try out a new restaurant',
    'Have a family game night',
    '回顾一天',
];

export default events.map((title, i) => ({
    id: String(i),
    title,
    start: i < 10 ? now : addDate(start + (i * TIME_DAY), randomInt(-100, 100), 'hour'),
    allDay: randomInt(0, 1) === 1,
    color: randomInt(0, 1) === 1 ? colors[randomInt(0, colors.length - 1)] : undefined,
}));
